---
- name: Install IUS Repo for CentOS
  yum:
    name:
      - https://centos7.iuscommunity.org/ius-release.rpm
    state: present
  when: ansible_distribution == "CentOS"

- name: Install IUS Repo for RedHat
  yum:
    name:
      - https://rhel7.iuscommunity.org/ius-release.rpm
    state: present
  when: ansible_distribution == "RedHat"

- name: Update ius to use the internal mirror
  replace:
    dest: "/etc/yum.repos.d/{{ item }}"
    regexp: '^#baseurl=(.+)$'
    replace: 'baseurl=\1'
  with_items:
    - ius-archive.repo
    - ius-dev.repo
    - ius-testing.repo
    - ius.repo