---
- name: Import OS Specific
  include_tasks: "{{ ansible_os_family | lower }}_repos.yml"

- import_tasks: add_redhat_role_repos.yml
  when:
    - repositories.redhat is defined
    - repositories.redhat.index > 0

# - import_tasks: add_debian_role_repos.yml
#   when:
#     - repositories.debian is defined
#     - repositories.debian.index > 0
